### ISSUE TITLE
Need a no-wrap class

### ISSUE THREAD

**Issue by bjcfuller** [uriweb/uri-modern#72]
## Issue Type

[] Bug  
[] New Feature  
[X] Enhancement  
    
## Description

Need a no-wrap class, e.g.:
```css
.no-wrap {
  white-space: nowrap;
}
```
